name: Quay.io Multi-Arch image back up with Tags

on:
  workflow_dispatch:
  schedule:
  # Runs at 8:00 AM UTC every Friday
  - cron: '0 8 * * 5'


env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: cobrasoftware

jobs:
  pull-and-push-quay:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: cobrasoftware
          password: ${{ secrets.GHCR_PAT }}

      - name: Pull and Push Quay.io Tagged Images
        env:
          IMAGE_TAGS: |
            quay.io/centos/centos:stream9,stream8,latest
            quay.io/bootc-extension/httpd:latest
            quay.io/fedora/fedora-bootc:latest
            quay.io/fedora/fedora-silverblue:latest
            quay.io/fedora/fedora-coreos-kubevirt:latest
            quay.io/fedora/fedora-sway-atomic:latest
            quay.io/centos-bootc/centos-bootc:latest
            quay.io/fedora/fedora-toolbox:latest
            quay.io/fedora/fedora-budgie-atomic:latest
            quay.io/fedora/fedora:latest
            quay.io/fedora/fedora-coreos:latest
            quay.io/fedora/httpd-24:latest
            quay.io/fedora/mariadb-103:latest
            quay.io/fedora/fedora-minimal:latest
            quay.io/fedora/fedora-silverblue:latest
            quay.io/fedora/bodhi-base:latest
        run: |
          while IFS= read -r line; do
            image=$(echo $line | cut -d: -f1)
            tags=$(echo $line | cut -d: -f2 | tr ',' ' ')
            for tag in $tags; do
              echo "Processing $image:$tag..."
              docker pull $image:$tag
              docker tag $image:$tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/$image-quay:$tag
              docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/$image-quay:$tag
            done
          done <<< "$IMAGE_TAGS"