name: Quay.io Multi-Arch image back up with Tags

on:
  workflow_dispatch:
  schedule:
  # Runs at 8:00 AM UTC every Friday
  - cron: '0 8 * * 5'


env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: cobrasoftware

jobs:
  pull-and-push-windows:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Log into GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: cobrasoftware
          password: ${{ secrets.GHCR_PAT }}

      - name: Pull and Push Windows Tagged Images
        shell: bash
        env:
          IMAGE_TAGS: |
            mcr.microsoft.com/windows/servercore:ltsc2022,latest,ltsc2019,ltsc2025
            mcr.microsoft.com/windows/nanoserver:ltsc2022,latest,ltsc2019,ltsc2025
            golang:windowsservercore,nanoserver
            python:windowsservercore,nanoserver
        run: |
          while IFS= read -r line; do
            image=$(echo $line | cut -d: -f1)
            tags=$(echo $line | cut -d: -f2 | tr ',' ' ')
            for tag in $tags; do
              echo "Processing $image:$tag..."
              docker pull $image:$tag
              docker tag $image:$tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/$image:$tag
              docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/$image:$tag
            done
          done <<< "$IMAGE_TAGS"

